// Writes server/migrations/000_base.sql: the full table structure of the current database,
// so a brand-new server can be set up with `npm run db:migrate` alone.
// Every statement is idempotent (safe on a database that already has the tables).
// Usage: npm run db:schema   (run again after adding tables outside migrations)
import 'dotenv/config';
import { writeFile } from 'node:fs/promises';
import { pool } from '../db.js';

const q = async (sql, params) => (await pool.query(sql, params)).rows;
const ident = (s) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s.replace(/"/g, '""')}"`);

const tables = (await q(`SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                         WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relname <> 'schema_migrations' ORDER BY c.relname`));

const out = [
  '-- Base schema (generated by server/scripts/dump-schema.js - do not edit by hand).',
  '-- Creates every table, sequence, constraint and index if it does not exist yet.',
  '',
];

// sequences used by serial columns
const seqs = await q(`SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public' AND c.relkind = 'S' ORDER BY 1`);
for (const s of seqs) out.push(`CREATE SEQUENCE IF NOT EXISTS ${ident(s.relname)};`);
out.push('');

for (const t of tables) {
  const cols = await q(
    `SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS type, a.attnotnull, pg_get_expr(d.adbin, d.adrelid) AS def
     FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
     WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`,
    [t.oid]
  );
  out.push(`CREATE TABLE IF NOT EXISTS ${ident(t.relname)} (`);
  out.push(cols.map((c) => `  ${ident(c.attname)} ${c.type}${c.def != null ? ` DEFAULT ${c.def}` : ''}${c.attnotnull ? ' NOT NULL' : ''}`).join(',\n'));
  out.push(');');
  // columns added later still get created on an older copy of the table
  for (const c of cols) {
    out.push(`ALTER TABLE ${ident(t.relname)} ADD COLUMN IF NOT EXISTS ${ident(c.attname)} ${c.type}${c.def != null ? ` DEFAULT ${c.def}` : ''};`);
  }
  out.push('');
}

// sequences belong to their columns
const owned = await q(
  `SELECT s.relname AS seq, t.relname AS tbl, a.attname AS col FROM pg_depend d
   JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
   JOIN pg_class t ON t.oid = d.refobjid JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
   JOIN pg_namespace n ON n.oid = s.relnamespace WHERE n.nspname = 'public' AND d.deptype = 'a'`
);
for (const o of owned) out.push(`ALTER SEQUENCE ${ident(o.seq)} OWNED BY ${ident(o.tbl)}.${ident(o.col)};`);
out.push('');

// constraints: primary/unique/check first, foreign keys last (tables must exist)
const cons = await q(
  `SELECT c.conname, c.contype, t.relname, pg_get_constraintdef(c.oid) AS def FROM pg_constraint c
   JOIN pg_class t ON t.oid = c.conrelid JOIN pg_namespace n ON n.oid = t.relnamespace
   WHERE n.nspname = 'public' AND t.relname <> 'schema_migrations' AND c.contype IN ('p','u','c','f')
   ORDER BY CASE c.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 ELSE 3 END, t.relname, c.conname`
);
for (const c of cons) {
  out.push(
    `DO $$ BEGIN ALTER TABLE ${ident(c.relname)} ADD CONSTRAINT ${ident(c.conname)} ${c.def}; ` +
      `EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;`
  );
}
out.push('');

// indexes that are not behind a constraint
const idx = await q(
  `SELECT pg_get_indexdef(i.indexrelid) AS def FROM pg_index i
   JOIN pg_class ic ON ic.oid = i.indexrelid JOIN pg_class t ON t.oid = i.indrelid JOIN pg_namespace n ON n.oid = t.relnamespace
   WHERE n.nspname = 'public' AND t.relname <> 'schema_migrations'
     AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid)
   ORDER BY t.relname, ic.relname`
);
for (const i of idx) out.push(i.def.replace(/^CREATE (UNIQUE )?INDEX /, 'CREATE $1INDEX IF NOT EXISTS ').replace(' ON public.', ' ON ') + ';');
out.push('');

const file = new URL('../migrations/000_base.sql', import.meta.url);
await writeFile(file, out.join('\n'));
console.log(`Wrote ${tables.length} tables, ${cons.length} constraints, ${idx.length} indexes to server/migrations/000_base.sql`);
await pool.end();
