-- Base schema (generated by server/scripts/dump-schema.js - do not edit by hand).
-- Creates every table, sequence, constraint and index if it does not exist yet.

CREATE SEQUENCE IF NOT EXISTS admin_notifications_id_seq;
CREATE SEQUENCE IF NOT EXISTS audit_logs_id_seq;
CREATE SEQUENCE IF NOT EXISTS customer_addresses_id_seq;
CREATE SEQUENCE IF NOT EXISTS discount_usages_id_seq;
CREATE SEQUENCE IF NOT EXISTS discounts_id_seq;
CREATE SEQUENCE IF NOT EXISTS inventory_transactions_id_seq;
CREATE SEQUENCE IF NOT EXISTS order_items_id_seq;
CREATE SEQUENCE IF NOT EXISTS order_status_history_id_seq;
CREATE SEQUENCE IF NOT EXISTS orders_id_seq;
CREATE SEQUENCE IF NOT EXISTS otp_codes_id_seq;
CREATE SEQUENCE IF NOT EXISTS payments_id_seq;
CREATE SEQUENCE IF NOT EXISTS product_reviews_id_seq;
CREATE SEQUENCE IF NOT EXISTS product_variants_id_seq;
CREATE SEQUENCE IF NOT EXISTS refunds_id_seq;
CREATE SEQUENCE IF NOT EXISTS shipment_events_id_seq;
CREATE SEQUENCE IF NOT EXISTS stock_alerts_id_seq;
CREATE SEQUENCE IF NOT EXISTS users_id_seq;
CREATE SEQUENCE IF NOT EXISTS webhook_events_id_seq;

CREATE TABLE IF NOT EXISTS admin_notifications (
  id bigint DEFAULT nextval('admin_notifications_id_seq'::regclass) NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  body text,
  link text,
  severity text DEFAULT 'info'::text NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('admin_notifications_id_seq'::regclass);
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS type text;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS link text;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS severity text DEFAULT 'info'::text;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
ALTER TABLE admin_notifications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS admin_password_resets (
  token_hash text NOT NULL,
  user_id bigint NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE admin_password_resets ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE admin_password_resets ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE admin_password_resets ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE admin_password_resets ADD COLUMN IF NOT EXISTS used_at timestamp with time zone;
ALTER TABLE admin_password_resets ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS admin_roles (
  key text NOT NULL,
  name text NOT NULL,
  permissions jsonb DEFAULT '[]'::jsonb NOT NULL,
  is_system boolean DEFAULT false NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS permissions jsonb DEFAULT '[]'::jsonb;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS is_system boolean DEFAULT false;
ALTER TABLE admin_roles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS admin_sessions (
  token_hash text NOT NULL,
  user_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  ip text,
  user_agent text,
  mfa_passed boolean DEFAULT false NOT NULL
);
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS last_seen_at timestamp with time zone DEFAULT now();
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS ip text;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS user_agent text;
ALTER TABLE admin_sessions ADD COLUMN IF NOT EXISTS mfa_passed boolean DEFAULT false;

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint DEFAULT nextval('audit_logs_id_seq'::regclass) NOT NULL,
  admin_id bigint,
  admin_email text,
  action text NOT NULL,
  entity text,
  entity_id text,
  before jsonb,
  after jsonb,
  ip text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('audit_logs_id_seq'::regclass);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS admin_id bigint;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS admin_email text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS entity_id text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS before jsonb;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS after jsonb;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS user_agent text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS cart_items (
  user_id bigint NOT NULL,
  product_id text NOT NULL,
  option text DEFAULT ''::text NOT NULL,
  qty integer NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS option text DEFAULT ''::text;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS qty integer;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS categories (
  id text NOT NULL,
  name text NOT NULL,
  note text NOT NULL,
  image text NOT NULL,
  sort integer DEFAULT 0 NOT NULL,
  display_name text,
  description text,
  banner text,
  seo_title text,
  seo_description text,
  featured boolean DEFAULT false NOT NULL,
  active boolean DEFAULT true NOT NULL,
  display_mode text DEFAULT 'list'::text NOT NULL,
  accent text,
  icon text,
  site_image text,
  variant_label text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  site_sort integer
);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort integer DEFAULT 0;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS banner text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_title text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS seo_description text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS featured boolean DEFAULT false;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS display_mode text DEFAULT 'list'::text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS accent text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS site_image text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS variant_label text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE categories ADD COLUMN IF NOT EXISTS site_sort integer;

CREATE TABLE IF NOT EXISTS customer_addresses (
  id bigint DEFAULT nextval('customer_addresses_id_seq'::regclass) NOT NULL,
  user_id bigint NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  address_line text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  pin text NOT NULL,
  is_default boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('customer_addresses_id_seq'::regclass);
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS address_line text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS pin text;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS is_default boolean DEFAULT false;
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE customer_addresses ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS discount_usages (
  id bigint DEFAULT nextval('discount_usages_id_seq'::regclass) NOT NULL,
  discount_id bigint NOT NULL,
  order_id bigint NOT NULL,
  user_id bigint,
  amount integer NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  released_at timestamp with time zone
);
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('discount_usages_id_seq'::regclass);
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS discount_id bigint;
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS amount integer;
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE discount_usages ADD COLUMN IF NOT EXISTS released_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS discounts (
  id bigint DEFAULT nextval('discounts_id_seq'::regclass) NOT NULL,
  code text NOT NULL,
  description text,
  type text NOT NULL,
  value integer NOT NULL,
  scope text DEFAULT 'all'::text NOT NULL,
  product_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
  collection_ids jsonb DEFAULT '[]'::jsonb NOT NULL,
  min_order integer DEFAULT 0 NOT NULL,
  max_discount integer,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  usage_limit integer,
  per_customer_limit integer,
  used_count integer DEFAULT 0 NOT NULL,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('discounts_id_seq'::regclass);
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS type text;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS value integer;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS scope text DEFAULT 'all'::text;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS product_ids jsonb DEFAULT '[]'::jsonb;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS collection_ids jsonb DEFAULT '[]'::jsonb;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS min_order integer DEFAULT 0;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS max_discount integer;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS starts_at timestamp with time zone;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS ends_at timestamp with time zone;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS usage_limit integer;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS per_customer_limit integer;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS used_count integer DEFAULT 0;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS integrations (
  provider text NOT NULL,
  config jsonb DEFAULT '{}'::jsonb NOT NULL,
  secret_enc text,
  status text DEFAULT 'disconnected'::text NOT NULL,
  last_error text,
  last_checked_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS config jsonb DEFAULT '{}'::jsonb;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS secret_enc text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS status text DEFAULT 'disconnected'::text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS last_error text;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS last_checked_at timestamp with time zone;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS inventory_transactions (
  id bigint DEFAULT nextval('inventory_transactions_id_seq'::regclass) NOT NULL,
  variant_id integer,
  product_id text,
  option text,
  previous integer NOT NULL,
  new integer NOT NULL,
  change integer NOT NULL,
  reason text,
  source text NOT NULL,
  order_id bigint,
  admin_id bigint,
  admin_email text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('inventory_transactions_id_seq'::regclass);
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS variant_id integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS option text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS previous integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS new integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS change integer;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS admin_id bigint;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS admin_email text;
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS order_items (
  id bigint DEFAULT nextval('order_items_id_seq'::regclass) NOT NULL,
  order_id bigint NOT NULL,
  product_id text NOT NULL,
  option text DEFAULT ''::text NOT NULL,
  name text NOT NULL,
  unit_price integer NOT NULL,
  qty integer NOT NULL,
  line_total integer NOT NULL,
  variant_id integer,
  tax_rate numeric(5,2) DEFAULT 0 NOT NULL,
  hsn text
);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('order_items_id_seq'::regclass);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS option text DEFAULT ''::text;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_price integer;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS qty integer;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS line_total integer;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variant_id integer;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS tax_rate numeric(5,2) DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS hsn text;

CREATE TABLE IF NOT EXISTS order_status_history (
  id bigint DEFAULT nextval('order_status_history_id_seq'::regclass) NOT NULL,
  order_id bigint NOT NULL,
  status text NOT NULL,
  note text,
  source text DEFAULT 'system'::text NOT NULL,
  admin_email text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('order_status_history_id_seq'::regclass);
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS source text DEFAULT 'system'::text;
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS admin_email text;
ALTER TABLE order_status_history ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS orders (
  id bigint DEFAULT nextval('orders_id_seq'::regclass) NOT NULL,
  number text NOT NULL,
  user_id bigint,
  email text NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  address_line text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  pin text NOT NULL,
  payment_method text NOT NULL,
  status text DEFAULT 'placed'::text NOT NULL,
  subtotal integer NOT NULL,
  delivery integer NOT NULL,
  total integer NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  payment_status text DEFAULT 'pending'::text NOT NULL,
  razorpay_order_id text,
  razorpay_payment_id text,
  payment_token_hash text,
  stock_released boolean DEFAULT false NOT NULL,
  fulfilment_status text DEFAULT 'unfulfilled'::text NOT NULL,
  shiprocket_order_id text,
  shipment_id text,
  awb_code text,
  courier_name text,
  tracking_url text,
  fulfilment_error text,
  admin_note text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  discount_amount integer DEFAULT 0 NOT NULL,
  discount_code text,
  tax_amount integer DEFAULT 0 NOT NULL,
  shipment_status text,
  pickup_status text,
  expected_delivery date,
  shipping_synced_at timestamp with time zone,
  cancel_reason text,
  cancelled_at timestamp with time zone
);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('orders_id_seq'::regclass);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS number text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS address_line text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS city text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pin text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS status text DEFAULT 'placed'::text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal integer;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery integer;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total integer;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'pending'::text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_order_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS razorpay_payment_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_token_hash text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stock_released boolean DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fulfilment_status text DEFAULT 'unfulfilled'::text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shiprocket_order_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipment_id text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS awb_code text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier_name text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_url text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fulfilment_error text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_note text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount integer DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_code text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount integer DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipment_status text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pickup_status text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS expected_delivery date;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_synced_at timestamp with time zone;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason text;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS otp_codes (
  id bigint DEFAULT nextval('otp_codes_id_seq'::regclass) NOT NULL,
  flow_id text NOT NULL,
  channel text NOT NULL,
  target text NOT NULL,
  purpose text NOT NULL,
  code_hash text NOT NULL,
  attempts integer DEFAULT 0 NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  ip text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('otp_codes_id_seq'::regclass);
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS flow_id text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS channel text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS target text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS purpose text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS code_hash text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS attempts integer DEFAULT 0;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS verified_at timestamp with time zone;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS ip text;
ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS password_resets (
  token_hash text NOT NULL,
  user_id bigint NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS used_at timestamp with time zone;
ALTER TABLE password_resets ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS payments (
  id bigint DEFAULT nextval('payments_id_seq'::regclass) NOT NULL,
  order_id bigint,
  provider text DEFAULT 'razorpay'::text NOT NULL,
  provider_payment_id text NOT NULL,
  provider_order_id text,
  amount integer NOT NULL,
  currency text DEFAULT 'INR'::text NOT NULL,
  status text NOT NULL,
  method text,
  error text,
  raw jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('payments_id_seq'::regclass);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider text DEFAULT 'razorpay'::text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider_payment_id text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS provider_order_id text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount integer;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency text DEFAULT 'INR'::text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS method text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS error text;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS raw jsonb;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS pending_signups (
  flow_id text NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  password_hash text NOT NULL,
  user_id bigint,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS flow_id text;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
ALTER TABLE pending_signups ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS product_reviews (
  id bigint DEFAULT nextval('product_reviews_id_seq'::regclass) NOT NULL,
  product_id text NOT NULL,
  user_id bigint NOT NULL,
  rating smallint NOT NULL,
  title text,
  body text,
  status text DEFAULT 'published'::text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('product_reviews_id_seq'::regclass);
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS rating smallint;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS status text DEFAULT 'published'::text;
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS product_variants (
  id integer DEFAULT nextval('product_variants_id_seq'::regclass) NOT NULL,
  product_id text NOT NULL,
  option text DEFAULT ''::text NOT NULL,
  price integer NOT NULL,
  stock integer DEFAULT 100 NOT NULL,
  sort integer DEFAULT 0 NOT NULL,
  sku text,
  barcode text,
  compare_at_price integer,
  cost_price integer,
  low_stock_threshold integer DEFAULT 5 NOT NULL,
  track_inventory boolean DEFAULT true NOT NULL,
  weight_g integer,
  length_cm numeric(8,2),
  width_cm numeric(8,2),
  height_cm numeric(8,2),
  shipping_class text,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  image text
);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS id integer DEFAULT nextval('product_variants_id_seq'::regclass);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS option text DEFAULT ''::text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS price integer;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS stock integer DEFAULT 100;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS sort integer DEFAULT 0;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS barcode text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS compare_at_price integer;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS cost_price integer;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS low_stock_threshold integer DEFAULT 5;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS track_inventory boolean DEFAULT true;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS weight_g integer;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS length_cm numeric(8,2);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS width_cm numeric(8,2);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS height_cm numeric(8,2);
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS shipping_class text;
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE product_variants ADD COLUMN IF NOT EXISTS image text;

CREATE TABLE IF NOT EXISTS products (
  id text NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  category_id text NOT NULL,
  description text NOT NULL,
  image text NOT NULL,
  small_image text,
  color text NOT NULL,
  kind text NOT NULL,
  features jsonb DEFAULT '[]'::jsonb NOT NULL,
  specifications jsonb DEFAULT '[]'::jsonb NOT NULL,
  sort integer DEFAULT 0 NOT NULL,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  display_name text,
  site_images jsonb DEFAULT '[]'::jsonb NOT NULL,
  ingredients jsonb DEFAULT '[]'::jsonb NOT NULL,
  status text DEFAULT 'active'::text NOT NULL,
  short_description text,
  brand text,
  tags jsonb DEFAULT '[]'::jsonb NOT NULL,
  video_url text,
  model_url text,
  model_poster text,
  model_enabled boolean DEFAULT false NOT NULL,
  model_settings jsonb DEFAULT '{}'::jsonb NOT NULL,
  seo_title text,
  seo_description text,
  og_image text,
  tax_rate numeric(5,2) DEFAULT 0 NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  hsn text
);
ALTER TABLE products ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS image text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS small_image text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS kind text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS features jsonb DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS specifications jsonb DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS sort integer DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE products ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE products ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS site_images jsonb DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS ingredients jsonb DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS short_description text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags jsonb DEFAULT '[]'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS video_url text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_url text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_poster text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_enabled boolean DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS model_settings jsonb DEFAULT '{}'::jsonb;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS og_image text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate numeric(5,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE products ADD COLUMN IF NOT EXISTS hsn text;

CREATE TABLE IF NOT EXISTS refunds (
  id bigint DEFAULT nextval('refunds_id_seq'::regclass) NOT NULL,
  order_id bigint,
  provider text DEFAULT 'razorpay'::text NOT NULL,
  provider_refund_id text NOT NULL,
  payment_id text,
  amount integer NOT NULL,
  status text NOT NULL,
  reason text,
  admin_email text,
  raw jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('refunds_id_seq'::regclass);
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS provider text DEFAULT 'razorpay'::text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS provider_refund_id text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS payment_id text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS amount integer;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS admin_email text;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS raw jsonb;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS sessions (
  token_hash text NOT NULL,
  user_id bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL
);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS token_hash text;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS settings (
  key text NOT NULL,
  value jsonb NOT NULL
);
ALTER TABLE settings ADD COLUMN IF NOT EXISTS key text;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS value jsonb;

CREATE TABLE IF NOT EXISTS shipment_events (
  id bigint DEFAULT nextval('shipment_events_id_seq'::regclass) NOT NULL,
  order_id bigint NOT NULL,
  status text NOT NULL,
  status_code text,
  location text,
  description text,
  event_time timestamp with time zone,
  source text DEFAULT 'sync'::text NOT NULL,
  raw jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('shipment_events_id_seq'::regclass);
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS status text;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS status_code text;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS event_time timestamp with time zone;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS source text DEFAULT 'sync'::text;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS raw jsonb;
ALTER TABLE shipment_events ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

CREATE TABLE IF NOT EXISTS stock_alerts (
  id bigint DEFAULT nextval('stock_alerts_id_seq'::regclass) NOT NULL,
  variant_id integer NOT NULL,
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  notified_at timestamp with time zone
);
ALTER TABLE stock_alerts ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('stock_alerts_id_seq'::regclass);
ALTER TABLE stock_alerts ADD COLUMN IF NOT EXISTS variant_id integer;
ALTER TABLE stock_alerts ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE stock_alerts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE stock_alerts ADD COLUMN IF NOT EXISTS notified_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS users (
  id bigint DEFAULT nextval('users_id_seq'::regclass) NOT NULL,
  email text NOT NULL,
  name text NOT NULL,
  password_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  is_admin boolean DEFAULT false NOT NULL,
  phone text,
  admin_role text,
  status text DEFAULT 'active'::text NOT NULL,
  admin_note text,
  failed_logins integer DEFAULT 0 NOT NULL,
  locked_until timestamp with time zone,
  totp_secret_enc text,
  totp_enabled boolean DEFAULT false NOT NULL,
  last_login_at timestamp with time zone,
  email_verified_at timestamp with time zone,
  phone_verified_at timestamp with time zone,
  totp_last_step bigint
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('users_id_seq'::regclass);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin boolean DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_role text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admin_note text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_logins integer DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret_enc text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled boolean DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified_at timestamp with time zone;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_last_step bigint;

CREATE TABLE IF NOT EXISTS webhook_events (
  id bigint DEFAULT nextval('webhook_events_id_seq'::regclass) NOT NULL,
  provider text NOT NULL,
  event_id text NOT NULL,
  event_type text,
  payload jsonb,
  signature text,
  received_at timestamp with time zone DEFAULT now() NOT NULL,
  processed_at timestamp with time zone,
  processing_status text DEFAULT 'received'::text NOT NULL,
  error_message text,
  attempts integer DEFAULT 0 NOT NULL
);
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS id bigint DEFAULT nextval('webhook_events_id_seq'::regclass);
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS event_id text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS payload jsonb;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS signature text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS received_at timestamp with time zone DEFAULT now();
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS processed_at timestamp with time zone;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS processing_status text DEFAULT 'received'::text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS error_message text;
ALTER TABLE webhook_events ADD COLUMN IF NOT EXISTS attempts integer DEFAULT 0;

CREATE TABLE IF NOT EXISTS wishlist_items (
  user_id bigint NOT NULL,
  product_id text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE wishlist_items ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE wishlist_items ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE wishlist_items ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

ALTER SEQUENCE product_variants_id_seq OWNED BY product_variants.id;
ALTER SEQUENCE users_id_seq OWNED BY users.id;
ALTER SEQUENCE orders_id_seq OWNED BY orders.id;
ALTER SEQUENCE order_items_id_seq OWNED BY order_items.id;
ALTER SEQUENCE audit_logs_id_seq OWNED BY audit_logs.id;
ALTER SEQUENCE admin_notifications_id_seq OWNED BY admin_notifications.id;
ALTER SEQUENCE inventory_transactions_id_seq OWNED BY inventory_transactions.id;
ALTER SEQUENCE order_status_history_id_seq OWNED BY order_status_history.id;
ALTER SEQUENCE payments_id_seq OWNED BY payments.id;
ALTER SEQUENCE refunds_id_seq OWNED BY refunds.id;
ALTER SEQUENCE webhook_events_id_seq OWNED BY webhook_events.id;
ALTER SEQUENCE shipment_events_id_seq OWNED BY shipment_events.id;
ALTER SEQUENCE otp_codes_id_seq OWNED BY otp_codes.id;
ALTER SEQUENCE discounts_id_seq OWNED BY discounts.id;
ALTER SEQUENCE discount_usages_id_seq OWNED BY discount_usages.id;
ALTER SEQUENCE customer_addresses_id_seq OWNED BY customer_addresses.id;
ALTER SEQUENCE product_reviews_id_seq OWNED BY product_reviews.id;
ALTER SEQUENCE stock_alerts_id_seq OWNED BY stock_alerts.id;

DO $$ BEGIN ALTER TABLE admin_notifications ADD CONSTRAINT admin_notifications_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE admin_password_resets ADD CONSTRAINT admin_password_resets_pkey PRIMARY KEY (token_hash); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE admin_roles ADD CONSTRAINT admin_roles_pkey PRIMARY KEY (key); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE admin_sessions ADD CONSTRAINT admin_sessions_pkey PRIMARY KEY (token_hash); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cart_items ADD CONSTRAINT cart_items_pkey PRIMARY KEY (user_id, product_id, option); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE customer_addresses ADD CONSTRAINT customer_addresses_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discount_usages ADD CONSTRAINT discount_usages_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discounts ADD CONSTRAINT discounts_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integrations ADD CONSTRAINT integrations_pkey PRIMARY KEY (provider); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_items ADD CONSTRAINT order_items_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_status_history ADD CONSTRAINT order_status_history_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE otp_codes ADD CONSTRAINT otp_codes_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE password_resets ADD CONSTRAINT password_resets_pkey PRIMARY KEY (token_hash); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pending_signups ADD CONSTRAINT pending_signups_pkey PRIMARY KEY (flow_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_variants ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE refunds ADD CONSTRAINT refunds_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE sessions ADD CONSTRAINT sessions_pkey PRIMARY KEY (token_hash); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE settings ADD CONSTRAINT settings_pkey PRIMARY KEY (key); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE shipment_events ADD CONSTRAINT shipment_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE stock_alerts ADD CONSTRAINT stock_alerts_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE webhook_events ADD CONSTRAINT webhook_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE wishlist_items ADD CONSTRAINT wishlist_items_pkey PRIMARY KEY (user_id, product_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discount_usages ADD CONSTRAINT discount_usages_discount_id_order_id_key UNIQUE (discount_id, order_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_number_key UNIQUE (number); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE payments ADD CONSTRAINT payments_provider_provider_payment_id_key UNIQUE (provider, provider_payment_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_product_id_user_id_key UNIQUE (product_id, user_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_variants ADD CONSTRAINT product_variants_product_id_option_key UNIQUE (product_id, option); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE products ADD CONSTRAINT products_slug_key UNIQUE (slug); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE refunds ADD CONSTRAINT refunds_provider_provider_refund_id_key UNIQUE (provider, provider_refund_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE webhook_events ADD CONSTRAINT webhook_events_provider_event_id_key UNIQUE (provider, event_id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cart_items ADD CONSTRAINT cart_items_qty_check CHECK (((qty >= 1) AND (qty <= 99))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discounts ADD CONSTRAINT discounts_value_check CHECK ((value > 0)); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integrations ADD CONSTRAINT integrations_provider_check CHECK ((provider = ANY (ARRAY['razorpay'::text, 'shiprocket'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE integrations ADD CONSTRAINT integrations_status_check CHECK ((status = ANY (ARRAY['connected'::text, 'error'::text, 'disconnected'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_items ADD CONSTRAINT order_items_qty_check CHECK (((qty >= 1) AND (qty <= 99))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_payment_method_check CHECK ((payment_method = ANY (ARRAY['online'::text, 'cod'::text, 'upi'::text, 'card'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_payment_status_check CHECK ((payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'cod'::text, 'failed'::text, 'refunded'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_status_check CHECK ((status = ANY (ARRAY['pending_payment'::text, 'placed'::text, 'confirmed'::text, 'processing'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_status_check CHECK ((status = ANY (ARRAY['published'::text, 'hidden'::text]))); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_variants ADD CONSTRAINT product_variants_price_check CHECK ((price >= 0)); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_variants ADD CONSTRAINT product_variants_stock_check CHECK ((stock >= 0)); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE admin_password_resets ADD CONSTRAINT admin_password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE admin_sessions ADD CONSTRAINT admin_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cart_items ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE cart_items ADD CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE customer_addresses ADD CONSTRAINT customer_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discount_usages ADD CONSTRAINT discount_usages_discount_id_fkey FOREIGN KEY (discount_id) REFERENCES discounts(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discount_usages ADD CONSTRAINT discount_usages_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE discount_usages ADD CONSTRAINT discount_usages_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE inventory_transactions ADD CONSTRAINT inventory_transactions_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_items ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_items ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE order_status_history ADD CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE password_resets ADD CONSTRAINT password_resets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE payments ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE pending_signups ADD CONSTRAINT pending_signups_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_reviews ADD CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE product_variants ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id); EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE refunds ADD CONSTRAINT refunds_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE sessions ADD CONSTRAINT sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE shipment_events ADD CONSTRAINT shipment_events_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE stock_alerts ADD CONSTRAINT stock_alerts_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE wishlist_items ADD CONSTRAINT wishlist_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE wishlist_items ADD CONSTRAINT wishlist_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object OR duplicate_table OR invalid_table_definition THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS admin_notifications_created_idx ON admin_notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_sessions_user_idx ON admin_sessions USING btree (user_id);
CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON audit_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_entity_idx ON audit_logs USING btree (entity, entity_id);
CREATE INDEX IF NOT EXISTS customer_addresses_user_idx ON customer_addresses USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS discounts_code_key ON discounts USING btree (upper(code));
CREATE INDEX IF NOT EXISTS inventory_tx_created_idx ON inventory_transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_tx_variant_idx ON inventory_transactions USING btree (variant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS order_items_order_idx ON order_items USING btree (order_id);
CREATE INDEX IF NOT EXISTS order_status_history_order_idx ON order_status_history USING btree (order_id, created_at);
CREATE INDEX IF NOT EXISTS orders_awb_idx ON orders USING btree (awb_code) WHERE (awb_code IS NOT NULL);
CREATE INDEX IF NOT EXISTS orders_created_idx ON orders USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS orders_email_idx ON orders USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS orders_razorpay_order_idx ON orders USING btree (razorpay_order_id) WHERE (razorpay_order_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS orders_status_idx ON orders USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS orders_user_idx ON orders USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS otp_codes_flow_idx ON otp_codes USING btree (flow_id, channel, created_at DESC);
CREATE INDEX IF NOT EXISTS otp_codes_target_idx ON otp_codes USING btree (target, created_at DESC);
CREATE INDEX IF NOT EXISTS password_resets_user_idx ON password_resets USING btree (user_id);
CREATE INDEX IF NOT EXISTS payments_order_idx ON payments USING btree (order_id);
CREATE INDEX IF NOT EXISTS product_reviews_product_idx ON product_reviews USING btree (product_id, status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS product_variants_sku_key ON product_variants USING btree (sku) WHERE ((sku IS NOT NULL) AND (sku <> ''::text));
CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions USING btree (expires_at);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS shipment_events_dedupe ON shipment_events USING btree (order_id, status, COALESCE(event_time, '1970-01-01 05:30:00+05:30'::timestamp with time zone));
CREATE UNIQUE INDEX IF NOT EXISTS stock_alerts_open_idx ON stock_alerts USING btree (variant_id, lower(email)) WHERE (notified_at IS NULL);
CREATE UNIQUE INDEX IF NOT EXISTS users_phone_key ON users USING btree (phone) WHERE (phone IS NOT NULL);
CREATE INDEX IF NOT EXISTS webhook_events_received_idx ON webhook_events USING btree (provider, received_at DESC);
